### Download de dataset m.b.v. load_iris() uit sklearn.datasets.

In [11]:

import numpy as np
import sklearn.datasets

iris = sklearn.datasets.load_iris()

### Vul je featurematrix X op basis van de data.

In [12]:
X = iris.data

#### De uitkomstvector y ga je vullen op basis van target. 
Standaard bevat deze array de waardes 0, 1 en 2 (resp. 'setosa', 'versicolor', 'virginica'). Maak deze binair door 0 en 1 allebei 0 te maken (niet-virginica) en van elke 2 een 1 te maken (wel-virginica). Denk erom dat y het juiste datatype en de juiste shape krijgt.

In [13]:
y = iris.target

print(X.shape)
print(y.shape)
print(y.T)

y = np.where(y == 2, 1, 0)
print(y.T)

(150, 4)
(150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1]


### Definieer een functie sigmoid() die de sigmoïde-functie implementeert.

In [15]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

test_z = 0
sigmoid(test_z)

0.5

### Initialiseer een vector theta met 1.0'en in de juiste shape.

In [16]:
theta = np.ones(X.shape[1])

### Nu kun je beginnen aan de loop waarin je in 1500 iteraties:
- De voorspellingen (denk aan sigmoid!) en de errors berekent.
- De gradient berekent en theta aanpast. Werk in eerste instantie met een learning rate van 0.01.
- De kosten berekent.

In [21]:
def compute_cost(X, y, theta):
    J = 0
    m,n = X.shape

    J = np.sum(np.square(np.dot(X, theta) - y)) / (2 * m)
    
    return J

def gradient_descent(X, y, theta, alpha, num_iters):

    costs = []
    m, n = X.shape
    htheta = X.dot(theta.transpose())
    for _ in range(num_iters):
        htheta = X.dot(theta.transpose())
        a = (alpha / m)
        theta[0, 0] = theta[0, 0] - a * (htheta - y).sum()
        theta[0, 1] = theta[0, 1] - a * ((htheta - y) * (X[::, 1:])).sum() 
        costs.append(compute_cost(X, y, theta.transpose()))

    costs = np.array(costs)

    return theta, costs


In [27]:
for _ in range(1500):
    prediction = sigmoid(np.dot(X,theta))
    theta = theta - 0.01 * np.dot(X.T, prediction - y)

print(theta)
    

ValueError: shapes (150,4) and (5,1) not aligned: 4 (dim 1) != 5 (dim 0)

### Experimenteer eens met andere waardes van de learning rate (1.0 < alpha < 0.0).

In [28]:
LearningRates = [0.0, 0.1, 0.3, 0.5, 0.7, 0.9, 1.0]

for i in LearningRates:
    theta = np.ones((X.shape[1],1))
    for _ in range(1500):
        prediction = sigmoid(np.dot(X,theta))
        theta = theta - i * np.dot(X.T, prediction - y)
    print(theta)

[[1.]
 [1.]
 [1.]
 [1.]]
[[-96.35239017]
 [-95.90851751]
 [132.74827364]
 [129.01986318]]
[[-286.7694525 ]
 [-285.02584852]
 [ 396.68063893]
 [ 380.36862438]]
[[-480.38168584]
 [-476.22309273]
 [ 660.98057273]
 [ 637.11945213]]
[[-678.95769453]
 [-669.22358183]
 [ 914.86606188]
 [ 895.65924946]]
[[-873.95593099]
 [-859.08829175]
 [1181.44446257]
 [1146.44660853]]
[[-960.01758075]
 [-949.80856744]
 [1315.94831307]
 [1283.71128794]]


C:\Users\colin\AppData\Local\Temp\ipykernel_29800\514242896.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-z))
